USE [master]
GO

/****** Object:  Database [RigelonicHR]    Script Date: 3/31/2020 5:47:47 PM ******/
CREATE DATABASE [RigelonicHR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RigelonicHR', FILENAME = N'D:\work\repos\DB\RigelonicHR.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RigelonicHR_log', FILENAME = N'D:\work\repos\DB\RigelonicHR_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RigelonicHR] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RigelonicHR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RigelonicHR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RigelonicHR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RigelonicHR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RigelonicHR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RigelonicHR] SET ARITHABORT OFF 
GO

ALTER DATABASE [RigelonicHR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RigelonicHR] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RigelonicHR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RigelonicHR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RigelonicHR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RigelonicHR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RigelonicHR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RigelonicHR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RigelonicHR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RigelonicHR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RigelonicHR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RigelonicHR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RigelonicHR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RigelonicHR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RigelonicHR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RigelonicHR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RigelonicHR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RigelonicHR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RigelonicHR] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RigelonicHR] SET  MULTI_USER 
GO

ALTER DATABASE [RigelonicHR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RigelonicHR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RigelonicHR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RigelonicHR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RigelonicHR] SET  READ_WRITE 
GO


